[package]
name = "circuits_and_constraints"
version = "0.1.0"
edition = "2024"

[dependencies]
num-bigint-dig = "0.9.1"
num-traits = "0.2.6"
utils = {path = "../utils" }
either = "1.15.0"
itertools = "0.14.0"
rand = "0.9.2"
rand_chacha = "0.9.0"