[package]
name = "clustering"
version = "0.1.0"
edition = "2024"

[dependencies]
circuits_and_constraints = {path = "../circuits_and_constraints" }
circuit_graphing = {path = "../circuit_graphing"}
ansi_term = "0.12.1"
