[package]
name = "civer"
version = "1.0.0"
authors = ["Costa Group UCM"]
edition = "2018"

description = "civer is an arithmetic circuit verifier"
keywords = ["zkproofs", "zksanrks","circuits","compiler"]
categories = ["compilers"]

[dependencies]
circom_algebra = {path = "../circom_algebra"}
clap = "2.33.0"
ansi_term = "0.12.1"
wast = "39.0.0"
exitcode = "1.1.2"
num-bigint-dig = "0.6.0"
z3 = {version="0.11.2", features = ["static-link-z3"]}
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"